<?php
return [
    'sample'                        => 'modules/sample.php',
    'employee-reg'                  => 'modules/admin/employee-reg.php',
    'customer-reg'                  => 'modules/admin/customer-reg.php',
    'truck-reg'                     => 'modules/admin/truck-reg.php',
    'booking-reg'                   => 'modules/booking-reg.php',
    'trips'                         => 'modules/trips.php',
    'sales'                         => 'modules/sales.php',
    'manage-tariff'                 => 'modules/manage-tariff.php',
    'reports'                       => 'modules/admin/reports.php',
    'manage-company'                => 'modules/admin/manage-company.php',
    'manage-employee'               => 'modules/admin/manage-employee.php',
    'manage-truck'                  => 'modules/admin/manage-truck.php',
    'customer-individual/profile'   => 'modules/customer-individual/profile.php',
    'customer-individual/bookings'  => 'modules/customer-individual/bookings.php',
    'logout'                        => 'modules/logout.php',
    'signup'                        => 'modules/customer-individual/signup.php',
    'staff-login'                   => 'modules/staff-login.php',
    'bookings'                      => 'modules/customer-individual/bookings.php',
    'booking-details'               => 'modules/customer-individual/booking-details.php',
    'assistantDashboard'            => 'modules/assistant/assistantDashboard.php',
    'driverDashboard'               => 'modules/driver/driverDashboard.php',
];